### ISSUE TITLE
mock axios using axios interceptors

### ISSUE THREAD

**Issue by DatVuGcc** [knee-cola/jest-mock-axios#23] opened 2019-02-01 15:58 UTC
I'm trying to use mockAxios for testing with axios interceptors.

![image](https://user-images.githubusercontent.com/45617185/52134173-05ec6e80-2654-11e9-8b69-99f815cd1f75.png)

![image](https://user-images.githubusercontent.com/45617185/52134514-c83c1580-2654-11e9-94c2-124113405f52.png)

When I created mockAxios: 
export default {
  get: jest.fn(() => Promise.resolve(data: {}))
}
All of my tests failed with the follow message: cannot read property response of undefined inside of axios interceptors. It happens because mock axios doesn't return response. It could just return a plain object. So how can I use axios interceptors with mockAxios for testing?
![image](https://user-images.githubusercontent.com/45617185/52134459-a8a4ed00-2654-11e9-968c-0398e04236fa.png)

**Comment by marvinkome** [comment] 2019-03-05 16:34
I used this in my `__mocks__/axios.js` file:
```js
import mockAxios from 'jest-mock-axios';
export default {
    ...mockAxios,
    create: jest.fn(() => ({
        ...mockAxios,
        defaults: {
            headers: {
                common: {}
            }
        },
        interceptors: {
            request: {
                use: jest.fn()
            },
            response: {
                use: jest.fn()
            }
        }
    }))
};```

**Comment by chimilord** [comment] 2019-03-08 20:41
@marvinkome works smooth! Thanks.

**Comment by DatVuGcc** [comment] 2019-03-19 12:21
> ```js
> import mockAxios from 'jest-mock-axios';
> export default {
>     ...mockAxios,
>     create: jest.fn(() => ({
>         ...mockAxios,
>         defaults: {
>             headers: {
>                 common: {}
>             }
>         },
>         interceptors: {
>             request: {
>                 use: jest.fn()
>             },
>             response: {
>                 use: jest.fn()
>             }
>         }
>     }))
> };
> ```

Didn't help. Still have the same issue.

**Comment by kingjan1999** [comment] 2019-03-19 15:25
That's a duplicate of #5.

**Closed by kingjan1999** 2019-03-19 15:25 UTC
